### ISSUE TITLE
Precinct lookup fails when precinct not in VoterTurnout element

### ISSUE THREAD

**Issue by ghing** [openelections/clarify#13]
We try to grab the lists of precincts from the VoterTurnout element and then look them up when setting the jurisdiction of vote objects.  However, the precinct may not exist in the VoterTurnout entity, but may exist as a Precinct element under a VoteType element.  This appears in the results file 20120522__ar__primary__van_buren__precinct.xml.

This happens in Parser._parse_contest() and results in a KeyError.

I've already fixed this in my working copy and am just creating this issue for reference.  I'll push the change to GitHub and PyPI when I get home tonight.

**Comment by cjwinchester** [comment]
Howdy!

I think I'm running into the same or similar issue with precinct-level results from the [2014](http://results.enr.clarityelections.com/NE/Sarpy/51545/184335/en/reports.html) and [2016](http://results.enr.clarityelections.com/NE/Sarpy/61551/184336/en/reports.html) primaries in Sarpy County, Nebraska -- getting a vote type `KeyError` when I try to access the Parser instance.

Is there a known fix to this issue (before I go off spelunking in this XML file)? I'm running Python 3.4. Here's the code I'm stepping through for the 2014 results, up to the point where it breaks:

```python
from __future__ import print_function
from zipfile import ZipFile

try:
    from StringIO import StringIO as ioDuder
except ImportError:
    from io import BytesIO as ioDuder

import unicodecsv
import requests
import clarify


county = 'Sarpy'

url = 'http://results.enr.clarityelections.com/NE/Sarpy/51545/184335/en/summary.html'

election_type = 'primary'

def clarify_sarpy():
    '''
    1. Fetch zipped XML file.
    2. Unzip in memory.
    3. Load into Clarify.
    4. Loop over results, write to file.
    '''

    # discover path to zipfile and fetch
    s = clarify.Jurisdiction(url=url, level='county')
    r = requests.get(s.report_url('xml'), stream=True)
    z = ZipFile(ioDuder(r.content))

    # hand off to clarify
    p = clarify.Parser()
    p.parse(z.open('detail.xml'))

    for result in p.results:
        print(result)
```

And here's the traceback:

```
Traceback (most recent call last):
  File "parse_2014_primary_sarpy_precinct.py", line 132, in <module>
    clarify_sarpy()
  File "parse_2014_primary_sarpy_precinct.py", line 35, in clarify_sarpy
    p.parse(z.open('detail.xml'))
  File "/home/cjwinchester/.virtualenvs/clarify/local/lib/python3.4/site-packages/clarify/parser.py", line 48, in parse
    self._contests = self._parse_contests(tree, self._result_jurisdiction_lookup)
  File "/home/cjwinchester/.virtualenvs/clarify/local/lib/python3.4/site-packages/clarify/parser.py", line 256, in _parse_contests
    return [self._parse_contest(el, result_jurisdiction_lookup) for el in contest_els]
  File "/home/cjwinchester/.virtualenvs/clarify/local/lib/python3.4/site-packages/clarify/parser.py", line 256, in <listcomp>
    return [self._parse_contest(el, result_jurisdiction_lookup) for el in contest_els]
  File "/home/cjwinchester/.virtualenvs/clarify/local/lib/python3.4/site-packages/clarify/parser.py", line 283, in _parse_contest
    for r in self._parse_no_choice_results(contest_el, result_jurisdiction_lookup, contest):
  File "/home/cjwinchester/.virtualenvs/clarify/local/lib/python3.4/site-packages/clarify/parser.py", line 322, in _parse_no_choice_results
    subjurisdiction = result_jurisdiction_lookup[subjurisdiction_el.attrib['name']]
KeyError: 'ABSENTEE'
```

Thanks for any help you can offer.

**Comment by ghing** [comment]
Thanks for the report. As far as I know, this isn't a known issue. But
Derek would know better than I would. Can you attach the XML file to this
ticket also so I can take a look?

**Comment by cjwinchester** [comment]
Sure. [Here's the zipped XML file](https://github.com/openelections/clarify/files/634973/detailxml.zip) that threw the error posted above.

And if this isn't related to #13, should I open a new issue?

Thanks.

**Comment by ghing** [comment]
@cjwinchester, this is a separate issue from #13, please open a new issue if you can.  And thank you for sending the XML file. I'll try to take a look ASAP.

**Comment by GPHemsley** [comment]
@ghing Do you still have the aforementioned working copy? I'm not seeing that this ever got committed, but I've faked a commit for 0.1.2 (f52b38c1e0222d85106c7e7470f0bbacc5376eca) that I sourced from the PyPI release. Unless you have the originals, I'll uplift that commit to master a little later.

**Comment by ghing** [comment]
@GPHemsley anything I have would have been pushed to https://github.com/ghing/clarify/.

**Comment by GPHemsley** [comment]
@ghing I'm not seeing anything, so I'm gonna take that as a no.
